AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 32

Metrics/ClassLength:
  Max: 120

